name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: Ife-deb/uOAV_website
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/SEG4910-Capstone/website.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin main
